#!/usr/bin/env bash
# Usage: g resolve
# Summary: resolves all the dependencies in a golangdeps file
# Help: g resolve

set -e

source $_G_ROOT/share/g/meta.sh
setGoPath

while read line; do
    echo "Resolving $line"
    g get $line
done < golangdeps

